In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [7]:
data = pd.read_csv("data.csv")
data.head()

,time_tag,Obsdate,Obstime,Station,Observatory,Type,Quality,Region,Latitude,Report_Longitude,...,Numspot,Zurich,Penumbra,Compact,Spotclass,Magcode,Magclass,Obsid,Report_Status,ValidSpotClass
0,2024-12-18T00:03:00,2024-12-18T00:00:00,3,94302,LEA,spt,2,3920.0,22,-67,...,2,7,3,1,Hax,1,A,428,2,1
1,2024-12-18T00:03:00,2024-12-18T00:00:00,3,94302,LEA,spt,2,3924.0,-18,-55,...,10,4,3,2,Dao,3,BG,432,2,1
2,2024-12-18T00:03:00,2024-12-18T00:00:00,3,94302,LEA,spt,2,3922.0,-18,-27,...,18,4,3,3,Dai,2,B,431,2,1
3,2024-12-18T00:03:00,2024-12-18T00:00:00,3,94302,LEA,spt,2,3925.0,11,7,...,4,2,0,2,Bxo,2,B,434,2,1
4,2024-12-18T00:03:00,2024-12-18T00:00:00,3,94302,LEA,spt,2,3926.0,-20,42,...,2,7,2,1,Hsx,1,A,435,2,1

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579 entries, 0 to 578
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time_tag          579 non-null    object
 1   Obsdate           579 non-null    object
 2   Obstime           579 non-null    int64
 3   Station           579 non-null    int64
 4   Observatory       579 non-null    object
 5   Type              579 non-null    object
 6   Quality           579 non-null    int64
 7   Region            526 non-null    float64
 8   Latitude          579 non-null    int64
 9   Report_Longitude  579 non-null    int64
 10  Longitude         579 non-null    int64
 11  Report_Location   579 non-null    object
 12  Location          579 non-null    object
 13  Carlon            579 non-null    int64
 14  Extent            579 non-null    int64
 15  Area              579 non-null    int64
 16  Numspot           579 non-null    int64
 17  Zurich            579 non-null    int64
 18  Penumbra          579 non-null    int64
 19  Compact           579 non-null    int64
 20  Spotclass         579 non-null    object
 21  Magcode           579 non-null    int64
 22  Magclass          579 non-null    object
 23  Obsid             579 non-null    int64
 24  Report_Status     579 non-null    int64
 25  ValidSpotClass    579 non-null    int64
dtypes: float64(1), int64(17), object(8)
memory usage: 117.7+ KB

In [5]:
data.isnull().sum()

time_tag             0
Obsdate              0
Obstime              0
Station              0
Observatory          0
Type                 0
Quality              0
Region              53
Latitude             0
Report_Longitude     0
Longitude            0
Report_Location      0
Location             0
Carlon               0
Extent               0
Area                 0
Numspot              0
Zurich               0
Penumbra             0
Compact              0
Spotclass            0
Magcode              0
Magclass             0
Obsid                0
Report_Status        0
ValidSpotClass       0
dtype: int64

In [11]:
data["Region"].fillna(data["Region"].mean(), inplace=True)

C:\Users\acer\AppData\Local\Temp\ipykernel_47648\3827552008.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Region"].fillna(data["Region"].mean(), inplace=True)

In [12]:
data.isnull().sum()

time_tag            0
Obsdate             0
Obstime             0
Station             0
Observatory         0
Type                0
Quality             0
Region              0
Latitude            0
Report_Longitude    0
Longitude           0
Report_Location     0
Location            0
Carlon              0
Extent              0
Area                0
Numspot             0
Zurich              0
Penumbra            0
Compact             0
Spotclass           0
Magcode             0
Magclass            0
Obsid               0
Report_Status       0
ValidSpotClass      0
dtype: int64

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load data
data = pd.read_csv('data.csv')

# Preprocess data
data['Spotclass'] = data['Spotclass'].astype('category').cat.codes  # Example encoding
features = ['Latitude', 'Report_Longitude', 'Zurich', 'Penumbra', 'Compact']
X = data[features]
y = data['Spotclass']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Evaluate model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9396551724137931